package Model.POJO;
// Generated 26/06/2019 07:32:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Formato generated by hbm2java
 */
public class Formato  implements java.io.Serializable {


     private Integer forId;
     private String forNombre;
     private Set peliculas = new HashSet(0);

    public Formato() {
    }

	
    public Formato(String forNombre) {
        this.forNombre = forNombre;
    }
    public Formato(String forNombre, Set peliculas) {
       this.forNombre = forNombre;
       this.peliculas = peliculas;
    }
   
    public Integer getForId() {
        return this.forId;
    }
    
    public void setForId(Integer forId) {
        this.forId = forId;
    }
    public String getForNombre() {
        return this.forNombre;
    }
    
    public void setForNombre(String forNombre) {
        this.forNombre = forNombre;
    }
    public Set getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set peliculas) {
        this.peliculas = peliculas;
    }

      public String [] toStringArray() {
        String [] data = new String[2];
        data[0]=String.valueOf(this.forId);
        data[1]=this.forNombre;

        return data;
    }


}


